export const BLUELOGO = require("./blueImage.png")
export const MAPIMAGE = require("./map.png")
export const CARTOON = require("./cartoon.png")
export const NUMBERPLATE = require("./numberplate.png")
export const CARBACk = require("./carback.png")